FROM ubuntu:14.04
MAINTAINER Simonassi Luis Dario version: 0.1

RUN apt-get -y update && apt-get -y install tomcat7

ENV JAVA_HOME /apps/boundle/jdk
ENV GRAILS_HOME /apps/boundle/grails
ENV PATH $PATH:/$JAVA_HOME/bin:$GRAILS_HOME/bin

RUN cd /apps && grails create-app dummy-app && cd /apps/dummy-app && grails test-app && grails war && rm -rf /apps/dummy-app
