FROM ubuntu:14.04
MAINTAINER Simonassi Luis Dario version: 0.1

RUN apt-get -y update && apt-get -y install wget && mkdir /apps && chmod 755 /apps && cd /apps && wget --no-check-certificate "https://s3-us-west-2.amazonaws.com/dario-deploys2/jdk.tar.gz" --output-document=/apps/jdk.tar.gz &&  tar -xvzf /apps/jdk.tar.gz && rm /apps/jdk.tar.gz 

ENV JAVA_HOME /apps/jdk
ENV PATH $PATH:/$JAVA_HOME/bin

RUN apt-get -y install tomcat7
