FROM ubuntu:14.04
MAINTAINER Simonassi Luis Dario version: 0.1

RUN apt-get -y update && apt-get -y install wget && apt-get -y install unzip && mkdir /apps && chmod 755 /apps && cd /apps && wget --no-check-certificate "https://s3-us-west-2.amazonaws.com/dario-deploys2/boundle.tar.gz" --output-document=/apps/boundle.tar.gz && tar -xvzf /apps/boundle.tar.gz && rm /apps/boundle.tar.gz

ENV JAVA_HOME /apps/boundle/jdk
ENV GRAILS_HOME /apps/boundle/grails
ENV PATH $PATH:/$JAVA_HOME/bin:$GRAILS_HOME/bin

RUN cd /apps && grails create-app dummy-app && cd /apps/dummy-app && grails test-app && grails war && rm -rf /apps/dummy-app
